# Example Site settings
title: not-buk
#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - artefak.md

footer: 'Tak kenal maka tak sayang, <a href="/tentang">Tentang aku.</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
