# Example Site settings
title: ky is my id
#google_analytics: UA-NNNNNNNN-N
# permalink config
permalink: /:title:output_ext

#header 
header_pages:
  - jurnal.md
  - artefak.md

#footer
footer: 'Pergi jauh jangan lupa <a href="/">pulang.</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-twitter-plugin
  - jekyll-youtube
  - jekyll-toc
  - jekyll-archives

#tag config
tag_permalink_style: pretty  
tag_page_layout: tag_page
tag_page_dir: tag

# toc config
toc:
  min_level: 2 # default: 1
  max_level: 5 # default: 6

# jekyll archives 

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

#compress
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
  
#disqus
disqus:
shortname: syauqia48

#default 
defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        comments: true   # change to false to default to comments off site-wide
# end setting jekyll-theme-console
